### ISSUE TITLE
'show_delete' error during template rendering

### ISSUE THREAD

**Issue by dokamo** [Soaa-/django-nested-inlines#1]
When opening the MyAdmin form I get the following error (I'm missing something?):

<pre>
KeyError at /admin/mytest/a/add/
'show_delete'
Request Method: GET
Request URL:    http://127.0.0.1:8000/admin/mytest/a/add/
Django Version: 1.4.5
Exception Type: KeyError
Exception Value:    
'show_delete'
Exception Location: /usr/local/lib/python2.7/dist-packages/django/template/context.py in __getitem__, line 54
Python Executable:  /usr/bin/python
Python Version: 2.7.3
Python Path:    
['/opt/djsite/clod',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PIL',
 '/usr/lib/python2.7/dist-packages/gst-0.10',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client',
 '/usr/lib/python2.7/dist-packages/ubuntuone-client',
 '/usr/lib/python2.7/dist-packages/ubuntuone-control-panel',
 '/usr/lib/python2.7/dist-packages/ubuntuone-couch',
 '/usr/lib/python2.7/dist-packages/ubuntuone-installer',
 '/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol',
 '/usr/lib/python2.7/dist-packages/wx-2.6-gtk2-unicode']
Server time:    Sun, 24 Feb 2013 08:21:10 -0600

Error during template rendering

In template /usr/local/lib/python2.7/dist-packages/django/contrib/admin/templates/admin/change_form.html, error at line 67
show_delete

...
67  {% block submit_buttons_bottom %}{% submit_row %}{% endblock %}
...
</pre>

{% submit_row %} is highlighted in red

model.py:

<pre>
from django.db import models

class C(models.Model):
    name =      models.CharField(max_length=200)
    b =             models.ForeignKey('B')

class B(models.Model):
    name =      models.CharField(max_length=200)
    a =         models.ForeignKey('A')

class A(models.Model):
    name =      models.CharField(max_length=200)
</pre>

admin.py

<pre>
from django.contrib import admin
from nested_inlines.admin import NestedModelAdmin, NestedStackedInline, NestedTabularInline
from models import A, B, C

class MyNestedInline(NestedTabularInline):
    model = C

class MyInline(NestedStackedInline):
    model = B
    inlines = [MyNestedInline,]

class MyAdmin(NestedModelAdmin):
    inlines = [MyInline,]

admin.site.register(A, MyAdmin)
</pre>

**Comment by Soaa-** [comment]
Thanks for the report! I'll try to reproduce it myself.

**Comment by lucianolev** [comment]
Hi, i'm getting the same error, but using 2 NestedStackedInline

**Comment by Soaa-** [comment]
I caught the bug. The `add_view` method is missing context for Django 1.4's admin. The bug is now fixed, but there are Javascript issues remaining. I'll be closing this report now; thanks!

**Comment by dokamo** [comment]
Yes, it works for me now. Great!

**Comment by dokamo** [comment]
Just point out that the NestedModelAdmin model references a js file named 'nested.js' that isn't in the source code. Is this correct? Should the 'inlines.js' be renamed?
