### ISSUE TITLE
Adding new object doesn't add new nested inline

### ISSUE THREAD

**Issue by thomasfulton** [Soaa-/django-nested-inlines#10]
Say you have

```
class CInline(NestedTabularInline):
    model = C

class BInline(NestedStackedInline):
    model = B
    inlines = [BInline,]

class AAdmin(NestedModelAdmin):
    inlines = [AInline,]

admin.site.register(A, AAdmin)
```

then adding a new B in the admin panel adds a new B with all of B's fields, but doesn't add new As inline with the B.

**Comment by ghost** [comment]
Confirm that. Tested on Django 1.4.5 and 1.5.1. The same behaviour.

**Comment by ghost** [comment]
also js file required in
nested_inlines/admin.py:19:        js = ('admin/js/nested.js',)
is missing. there is no such file in static dir.

**Comment by tsotsos** [comment]
there is any change on this issue? i just tested 1.5.2 not working.. there is a clue where is the problem? so maybe we can fix it

**Comment by rabbagliettiandrea** [comment]
I'm experiencing the same behaviour (django 1.5.3). Let's talk together about this issue to solve it!
Anyway interesting comment here: https://code.djangoproject.com/ticket/9025#comment:155

**Comment by bee-keeper** [comment]
Same experience with Django 1.6.4 - looks like this is coming from the inline.js.  

![added_new_inline](https://cloud.githubusercontent.com/assets/1985097/2851724/e475993a-d120-11e3-8c1e-e8c2a903dcf1.png)

Each time I add a new inline it increments by twice itself.  Is that what you guys are experiencing? 

To make it appear less broken you can just set 'extra' and 'max_num' in admin.py to the same number so it's not actually possible to add any more inners, but of course that does nothing to fix the underlying problem.

I would love to get this solved as well, have just invested an hour in looking at the Javascript but there's a lot going on.  I've narrowed down (some) of the problems to get_no_forms function but am confused by this line:

``` javascript
return parseInt(formset_prop.attr("autocomplete", "off").val());
```

I understand what it does, but am confused as to the logic behind it - any ideas?

**Comment by CVirus** [comment]
Facing the same problem here .. suggestions ?

**Comment by CVirus** [comment]
I really don't know what happened but it suddenly worked !
